name: shop
description: "An e-commerce shop template."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  http: ^1.2.2
  intl: ^0.19.0
  flutter_dotenv: ^5.2.1
  dotenv: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env

  fonts:
    - family: Space Mono
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
        - asset: assets/fonts/SpaceMono-Italic.ttf
          style: italic
        - asset: assets/fonts/SpaceMono-Bold.ttf
          weight: 700
        - asset: assets/fonts/SpaceMono-BoldItalic.ttf
          weight: 700
          style: italic
